[package]
name = "t02"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
bincode = "1.3.3"
serde = {version = "1.0.160", features = ["derive"]}
savefile = "0.13.0"
serde_cbor = "0.11.2"